### ISSUE TITLE
Crash on Start Minecraft

### ISSUE THREAD

**Issue by OcrSu** [Thretcha/RoadRunner#6]
Lastlog:
https://paste.loliidc.cn/?e3e02d1112c1368a#FLmeKPas7Rjmv5disKQvce3RHKJYS6DNFrqoXUGKhz28

**Comment by Thretcha** [comment]
This mod was coded for minecraft version 1.12 and it appears to me that you are trying to use it with minecraft version 1.16.5.
Thus the mod doesn't work and crashes the game.
I never got around to updating the mod and therefore no newer version is likely to come out any time soon.

**Comment by OcrSu** [comment]
> This mod was coded for minecraft version 1.12 and it appears to me that you are trying to use it with minecraft version 1.16.5. Thus the mod doesn't work and crashes the game. I never got around to updating the mod and therefore no newer version is likely to come out any time soon.

Im sorry....,,it seems that "maxneedssnacks" put the wrong address of issues  in, curseforge,but now it is fixed
https://www.curseforge.com/minecraft/mc-mods/roadrunner
